version: "3"
 
services:
    client:
       container_name: client
       build:
           context: frontend/
       restart: always
       depends_on:
            - api
       ports:
           - 12000:12000
       environment:
           - API_BASE_URL=http://api:3000
    api:
       container_name: api
       build:
           context: backend/
       restart: always
       ports:
           - 3000:3000